# Generated by Django 2.0.6 on 2018-06-14 00:09

import app.fields
import app.utils
import django.core.validators
from django.db import migrations
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=app.fields.PseudonymizedField(blank=True, field_type=django.db.models.fields.DateField, methods=(app.utils.mask, app.utils.unmask), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ip_address',
            field=app.fields.PseudonymizedField(blank=True, field_type=django.db.models.fields.GenericIPAddressField, methods=(app.utils.mask, app.utils.unmask), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=app.fields.PseudonymizedField(blank=True, field_type=django.db.models.fields.CharField, max_length=128, methods=(app.utils.mask, app.utils.unmask)),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=app.fields.PseudonymizedField(blank=True, field_type=django.db.models.fields.CharField, max_length=17, methods=(app.utils.mask, app.utils.unmask), validators=[django.core.validators.RegexValidator(message="Phone number must have the format: '+9999999999'.", regex='^\\+?[1-9]\\d{1,14}$')]),
        ),
    ]
