# Generated by Django 2.0.6 on 2018-06-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_of_birth',
            new_name='_date_of_birth',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ip_address',
            new_name='_ip_address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='_phone',
        ),
    ]
