# Generated by Django 2.0.6 on 2018-06-25 21:14

import app.fields
import app.utils
import django.core.validators
from django.db import migrations
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180614_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=app.fields.PseudonymizedField(blank=True, field_type=django.db.models.fields.CharField, max_length=16, methods=(app.utils.mask, app.utils.unmask), validators=[django.core.validators.RegexValidator(message="Phone number must have the format: '+9999999999'.", regex='^\\+?[1-9]\\d{1,14}$')]),
        ),
    ]
